---
name: Devel-Backtrace
version: 0.06
author:
  - 'Christoph Bussenius <pepe@cpan.org>'
abstract: Object-oriented backtrace
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Class::Accessor: 0
  String::Escape: 0
build_requires:
  Test::More: 0
provides:
  Devel::Backtrace:
    file: lib/Devel/Backtrace.pm
    version: 0.06
  Devel::Backtrace::Point:
    file: lib/Devel/Backtrace/Point.pm
  Devel::DollarAt:
    file: lib/Devel/DollarAt.pm
    version: 0.01
  Devel::DollarAt::NullMessage:
    file: lib/Devel/DollarAt.pm
  Devel::DollarAt::RedispatchPoint:
    file: lib/Devel/DollarAt.pm
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
